apiVersion: v1
kind: Pod
metadata:
  name: non-shm-demo
spec:
  containers:
  - name: server
    image: cheneyyu/shm-demo
    resources:
      limits:
        cpu: "1"
        memory: "1G"
  - name: function-1
    image: cheneyyu/shm-demo
    resources:
      limits:
        cpu: "1"
        memory: "1G"